# Generated by Django 5.0.7 on 2025-02-19 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('location_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='home.location')),
            ],
        ),
    ]
