# Generated by Django 5.0.7 on 2025-03-03 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_subcategory'),
    ]

    operations = [
    ]
