# Generated by Django 5.0.7 on 2025-03-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_roomimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_image',
        ),
    ]
