# Generated by Django 5.0.7 on 2025-03-19 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_room_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='home.location'),
        ),
    ]
