# Generated by Django 5.0.7 on 2025-04-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(default='razorpay', editable=False, max_length=10),
        ),
    ]
